version: "3.9"

services:
  db:
    image: postgres
    container_name: db-container
    ports:
      - 5432:5432
    volumes:
      - ./storage:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: general_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: compounds

  cli:
    build: .
    container_name: cli-container
    depends_on:
      - db
    volumes:
      - ./storage:/app
    command:
      tail -f /dev/null

volumes:
  storage: